### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by jengleberg** [courtneyfay/project-2-book-recommendations#2]
When first opening the app and clicking on the login button instead of the sign-in button upon "logging in" it does not prompt you to sign up or re-direct you to the sign-up page.  Add in the failure route to take the user to sign-up if the user does not exist.

**Comment by courtneyfay** [comment]
I finally got this fixed!! so now when a user who has already signed up tries to sign up, they get an flash message and not a routing error. same with logins. Woo!
